[platformio]
default_envs = lilygo_t5_47_s3
boards_dir = boards

[env:lilygo_t5_47_s3]
platform = espressif32@6.12.0
board = T5-ePaper-S3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = default, esp32_exception_decoder
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLILYGO_T5_EPD47_S3
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  adafruit/Adafruit GFX Library@^1.12.4
  olikraus/U8g2_for_Adafruit_GFX@^1.8.0
  https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
  https://github.com/lewisxhe/SensorsLib.git
